languageCode = 'zh-hans'
title = "Biao's short novel archive"
theme = "PaperMod"
[languages.en]
languageName = "Chinese Simplified"

[languages.en.menu.main]
name = "Index"
url = "archives"
weight = "5"
