on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  push:
    branches:
     - autofetch

permissions:
  contents: write

jobs:
  auto-fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: .venv/bin/scrape_biao
      - run: git config --global user.name githubactions
      - run: git config --global user.emal actions@github.com
      - run: git checkout -b update
      - run: git add .
      - run: git commit -m "update"
      - run: git push -u origin update
        with:
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: pull-request
        uses: diillson/auto-pull-request@latest
        with:
            destination_branch: "main"
            github_token: ${{ secrets.GITHUB_TOKEN }}