on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  push:
    branches:
     - autofetch

jobs:
  auto-fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: .venv/bin/scrape_biao
      - run: git config --local user.name githubactions
      - run: git config --local user.emal actions@github.com
      - run: git checkout -b update
      - run: git add .
      - run: git commit -m "update"
      - run: git remove set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/soda92/biao-short-novels.git
      - run: git push -u origin update
      - name: pull-request
        uses: diillson/auto-pull-request@latest
        with:
            destination_branch: "main"
            github_token: ${{ secrets.GH_TOKEN }}